### ISSUE TITLE
Why my Linux is searching a outdated version of linux

### ISSUE THREAD

**Issue by killer069** [discordjs/opus#101]
**Please describe the problem you are having in as much detail as possible:**

I am trying to install discord js opus and my linux is trying to search for a version that doesn't exists in discord js release.

To be precise, it is searching for [file](https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-linux-x64-glibc-2.28.tar.gz) which never exists.

**Error Logs**

```js
206 info run canvas@2.8.0 install node_modules/canvas node-pre-gyp install --fallback-to-build
207 info run ffmpeg-static@4.4.0 install node_modules/ffmpeg-static node install.js
208 info run @discordjs/opus@0.5.3 install node_modules/@discordjs/voice/node_modules/@discordjs/opus node-pre-gyp install --fallback-to-build
209 info run @discordjs/opus@0.6.0 install { code: 1, signal: null }
210 info run @discordjs/opus@0.5.3 install { code: 1, signal: null }
211 verbose reify failed optional dependency /home/container/node_modules/@discordjs/voice/node_modules/@discordjs/opus
212 silly reify mark deleted [
212 silly reify   '/home/container/node_modules/@discordjs/voice/node_modules/@discordjs/opus'
212 silly reify ]
213 verbose reify failed optional dependency /home/container/node_modules/@discordjs/voice/node_modules/node-addon-api
214 silly reify mark deleted [
214 silly reify   '/home/container/node_modules/@discordjs/voice/node_modules/node-addon-api'
214 silly reify ]
215 timing build:run:install:node_modules/@discordjs/voice/node_modules/@discordjs/opus Completed in 9087ms
216 info run ffmpeg-static@4.4.0 install { code: 1, signal: null }
217 timing reify:rollback:createSparse Completed in 1942ms
218 timing reify:rollback:retireShallow Completed in 0ms
219 timing command:install Completed in 17449ms
220 verbose stack Error: command failed
220 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
220 verbose stack     at ChildProcess.emit (node:events:394:28)
220 verbose stack     at maybeClose (node:internal/child_process:1064:16)
220 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
221 verbose pkgid @discordjs/opus@0.6.0
222 verbose cwd /home/container
223 verbose Linux 5.10.0-kali9-amd64
224 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
225 verbose node v16.8.0
226 verbose npm  v7.21.0
227 error code 1
228 error path /home/container/node_modules/@discordjs/opus
229 error command failed
230 error command sh -c node-pre-gyp install --fallback-to-build
231 error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
232 error node-pre-gyp info it worked if it ends with ok
232 error node-pre-gyp info using node-pre-gyp@0.4.1
232 error node-pre-gyp info using node@16.8.0 | linux | x64
232 error node-pre-gyp info check checked for "/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node" (not found)
232 error node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-linux-x64-glibc-2.28.tar.gz
232 error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-linux-x64-glibc-2.28.tar.gz
232 error node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.6.0 and node@16.8.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
232 error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-linux-x64-glibc-2.28.tar.gz
232 error gyp info it worked if it ends with ok
232 error gyp info using node-gyp@7.1.2
232 error gyp info using node@16.8.0 | linux | x64
232 error gyp info ok
232 error gyp info it worked if it ends with ok
232 error gyp info using node-gyp@7.1.2
232 error gyp info using node@16.8.0 | linux | x64
232 error gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
232 error (node:95) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
232 error (Use `node --trace-deprecation ...` to show where the warning was created)
232 error gyp info spawn /usr/bin/python3
232 error gyp info spawn args [
232 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
232 error gyp info spawn args   'binding.gyp',
232 error gyp info spawn args   '-f',
232 error gyp info spawn args   'make',
232 error gyp info spawn args   '-I',
232 error gyp info spawn args   '/home/container/node_modules/@discordjs/opus/build/config.gypi',
232 error gyp info spawn args   '-I',
232 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
232 error gyp info spawn args   '-I',
232 error gyp info spawn args   '/home/container/.cache/node-gyp/16.8.0/include/node/common.gypi',
232 error gyp info spawn args   '-Dlibrary=shared_library',
232 error gyp info spawn args   '-Dvisibility=default',
232 error gyp info spawn args   '-Dnode_root_dir=/home/container/.cache/node-gyp/16.8.0',
232 error gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
232 error gyp info spawn args   '-Dnode_lib_file=/home/container/.cache/node-gyp/16.8.0/<(target_arch)/node.lib',
232 error gyp info spawn args   '-Dmodule_root_dir=/home/container/node_modules/@discordjs/opus',
232 error gyp info spawn args   '-Dnode_engine=v8',
232 error gyp info spawn args   '--depth=.',
232 error gyp info spawn args   '--no-parallel',
232 error gyp info spawn args   '--generator-output',
232 error gyp info spawn args   'build',
232 error gyp info spawn args   '-Goutput_dir=.'
232 error gyp info spawn args ]
232 error gyp info ok
232 error gyp info it worked if it ends with ok
232 error gyp info using node-gyp@7.1.2
232 error gyp info using node@16.8.0 | linux | x64
232 error gyp ERR! build error
232 error gyp ERR! stack Error: not found: make
232 error gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:10:17)
232 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:18
232 error gyp ERR! stack     at new Promise (<anonymous>)
232 error gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/which/which.js:54:21)
232 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:71:22
232 error gyp ERR! stack     at new Promise (<anonymous>)
232 error gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:33)
232 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:80:22
232 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
232 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
232 error gyp ERR! System Linux 5.10.0-kali9-amd64
232 error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node" "--module_name=opus" "--module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
232 error gyp ERR! cwd /home/container/node_modules/@discordjs/opus
232 error gyp ERR! node -v v16.8.0
232 error gyp ERR! node-gyp -v v7.1.2
232 error gyp ERR! not ok
232 error node-pre-gyp ERR! build error
232 error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
232 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/container/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
232 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
232 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
232 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
232 error node-pre-gyp ERR! System Linux 5.10.0-kali9-amd64
232 error node-pre-gyp ERR! command "/usr/local/bin/node" "/home/container/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
232 error node-pre-gyp ERR! cwd /home/container/node_modules/@discordjs/opus
232 error node-pre-gyp ERR! node -v v16.8.0
232 error node-pre-gyp ERR! node-pre-gyp -v v0.4.1
232 error node-pre-gyp ERR! not ok
233 verbose exit 1

```

**Further details:**

- @discordjs/opus version: 0.6.0
- Node.js version: 16.8.0
- Operating system: Linux
- Priority this issue should have – decide yourself

**Comment by killer069** [comment]
[2021-09-07T10_58_11_096Z-debug.log](https://github.com/discordjs/opus/files/7121002/2021-09-07T10_58_11_096Z-debug.log)

For complete logs see ^^

**Comment by Positive2022** [comment]
same error on linux on nodejs v16.8 but not on 16.6  :/

**Comment by Mac898** [comment]
A friend of mine worked on this issue and found that It is important that you use a supported version of Glibc and NodeJS 16. If you check the releases page (https://github.com/discordjs/opus/releases) you can see the currently supported versions of 2.27 & 2.31. I believe these are the versions in use on Ubuntu 18.04 currently.
