### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by dhvitOP** [discordjs/opus#102]
**Get This Everytime i try to install discordjs/opus**

```js
npm ERR! code 1
npm ERR! path /home/container/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.4.1
npm ERR! node-pre-gyp info using node@16.8.0 | linux | x64
npm ERR! node-pre-gyp info check checked for "/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v93-napi-v3-linux-x64-glibc-2.28.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v93-napi-v3-linux-x64-glibc-2.28.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.3 and node@16.8.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v93-napi-v3-linux-x64-glibc-2.28.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.8.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.8.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.8.0/node-v16.8.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.8.0/node-v16.8.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.8.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.8.0/SHASUMS256.txt
npm ERR! (node:51) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/container/node_modules/@discordjs/opus/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/container/.cache/node-gyp/16.8.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/container/.cache/node-gyp/16.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/container/.cache/node-gyp/16.8.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/container/node_modules/@discordjs/opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.8.0 | linux | x64
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 4.15.0-147-generic
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node" "--module_name=opus" "--module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /home/container/node_modules/@discordjs/opus
npm ERR! gyp ERR! node -v v16.8.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.28 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/container/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 4.15.0-147-generic
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/home/container/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/container/node_modules/@discordjs/opus
npm ERR! node-pre-gyp ERR! node -v v16.8.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.1
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2021-09-09T12_45_46_599Z-debug.log
```

**Further details:**

- @discordjs/opus version: latest
- Node.js version: 16.8.0
- Operating system: An hosting server (maybe its linux)
- Priority this issue should have – please be realistic and elaborate if possible: trying to make a music bot so no much emergency or something

**Comment by dreamboy-cyber** [comment]
i have same issue.

**Comment by HarshitDev2005** [comment]
I don't know why I am facing this issue I am unable to install discordjs/opus somebody help!

**Comment by a-gavin** [comment]
**Description:**
Experiencing the same issue. Running our bot on an ec2 instance which only has glibc 2.26. The builds for this package are only glibc 2.27 and 2.31.

I'm not super familiar with JS packaging, but is there any way we can build this package from scratch and npm install our local build?

**Further details:**
- @discordjs/opus version: latest
- Node.js version 16.6.1
- npm 7.20.3
- OS is Amazon Linux

**Debug log:**
```npm WARN deprecated @sapphire/snowflake@1.3.6: This version has been automatically deprecated by @favware/npm-deprecate. Please use a newer version.
npm WARN deprecated discord-api-types@0.18.1: No longer supported. Install the latest release (0.20.2)
npm ERR! code 1
npm ERR! path /home/ec2-user/MoraleBot/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! make: Entering directory `/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/build'
npm ERR!   CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
npm ERR! make: Leaving directory `/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/build'
npm ERR! Failed to execute '/home/ec2-user/.nvm/versions/node/v16.6.1/bin/node /home/ec2-user/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.26/opus.node --module_name=opus --module_path=/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.26 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.4.1
npm ERR! node-pre-gyp info using node@16.6.1 | linux | x64
npm ERR! node-pre-gyp info check checked for "/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.26/opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-linux-x64-glibc-2.26.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-linux-x64-glibc-2.26.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.6.0 and node@16.6.1 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v93-napi-v3-linux-x64-glibc-2.26.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | linux | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.7.10 found at "/usr/bin/python3"
npm ERR! (node:9785) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ec2-user/.cache/node-gyp/16.6.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.cache/node-gyp/16.6.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/ec2-user/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ec2-user/.cache/node-gyp/16.6.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/MoraleBot/node_modules/@discordjs/opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: cc: Command not found
npm ERR! make: *** [Release/obj.target/libopus/deps/opus/src/opus_multistream.o] Error 127
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 4.14.232-177.418.amzn2.x86_64
npm ERR! gyp ERR! command "/home/ec2-user/.nvm/versions/node/v16.6.1/bin/node" "/home/ec2-user/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.26/opus.node" "--module_name=opus" "--module_path=/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.26" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /home/ec2-user/MoraleBot/node_modules/@discordjs/opus
npm ERR! gyp ERR! node -v v16.6.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/home/ec2-user/.nvm/versions/node/v16.6.1/bin/node /home/ec2-user/.nvm/versions/node/v16.6.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.26/opus.node --module_name=opus --module_path=/home/ec2-user/MoraleBot/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.26 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ec2-user/MoraleBot/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Linux 4.14.232-177.418.amzn2.x86_64
npm ERR! node-pre-gyp ERR! command "/home/ec2-user/.nvm/versions/node/v16.6.1/bin/node" "/home/ec2-user/MoraleBot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/ec2-user/MoraleBot/node_modules/@discordjs/opus
npm ERR! node-pre-gyp ERR! node -v v16.6.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.1
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2021-09-26T07_02_45_541Z-debug.log
```

**Comment by killer069** [comment]
@dhvitOP @a-gavin @dreamboy-cyber @HarshitDev2005 

All this is due to difference of glibc version that you have on your os and glibc version that discordjs/opus support.

So either discordjs/opus needs to extend its support or you need to lower your node version.

**Comment by michaelFarrier** [comment]
> ```
> npm ERR! make: cc: Command not found
> npm ERR! make: *** [Release/obj.target/libopus/deps/opus/src/opus_multistream.o] Error 127
> npm ERR! gyp ERR! build error
> npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
> ```

@a-gavin 
@greenerino found a fix for this particular issue (This is on a fresh pull - no packages installed).
Run `sudo yum groupinstall "Development Tools"` on the EC2 box. Then, `npm install`.
Just make sure you have make and gcc (or cc) installed.

This may also fix your issue @dhvitOP.

Node: v16.10.0
npm: v7.24.0

**Comment by killer069** [comment]
@michaelFarrier 

He is getting 404 also. So no fix even if he installs make.

![image](https://user-images.githubusercontent.com/65385476/134803611-945fb573-b3cc-40e4-b7a7-1e4ea45e6b22.png)

**Comment by a-gavin** [comment]
> they are getting 404 also. So no fix even if they install make.

We were getting the same 404 error as well.

As you pointed out, the version of glibc on the machine we were trying to use is not supported by discord/opus. Thus, when running `npm install`, it fails to find a supported version of discord/opus with both our and @dhvitOP's configuration because it doesn't exist, hence the 404 error.

As a fall back, npm attempts to build discord/opus with each of our configurations, as shown by the following output from @dhvitOP:
`npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.3 and node@16.8.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)`

If you look further down in each of our error outputs you will see the root cause. I admittedly missed this too (helps to not do dev at 12AM haha!).

For our configuration, this was:
`npm ERR! make: cc: Command not found`

For @dhvitOP, the root cause is:
`npm ERR! gyp ERR! stack Error: not found: make`

For our project, @greenino's fix worked because we were missing a compiler. In @dhvitOP's case, the missing component is `make`. Try installing `make` with your system's package manager and see if that fixes it?
