### ISSUE TITLE
Error while Installing

### ISSUE THREAD

**Issue by RXNationGMG** [discordjs/opus#107]
**Please describe the problem you are having in as much detail as possible:**

When I install @discordjs/opus I get this

**Include a reproducible code sample here, if possible:**
Here
```js
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v83-napi-v3-linux-x64-glibc-2.28.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.3 and node@14.17.6 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:192:21)
gyp ERR! System Linux 4.15.0-147-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/container/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.28/opus.node" "--module_name=opus" "--module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.28" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/container/node_modules/@discordjs/opus
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.28 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/container/node_modules/@discordjs/opus/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.15.0-147-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/container/node_modules/@discordjs/opus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/container/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v14.17.6
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.28/opus.node --module_name=opus --module_path=/home/container/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.28 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
[            ......] | install: info lifecycle @discordjs/opus@0.3.3~install: F[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F
[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F
[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F
[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F
[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F
[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F
[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F
[            ......] / install: info lifecycle @discordjs/opus@0.3.3~install: F

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/container/.npm/_logs/2021-10-01T19_07_33_525Z-debug.log
```

**Further details:**

- @discordjs/opus version:
- Node.js version:
- Operating system:
- Priority this issue should have – please be realistic and elaborate if possible:

**Comment by killer069** [comment]
Install make on ubuntu and fix your issue.
