### ISSUE TITLE
Opus failed to install win 11 Node V17

### ISSUE THREAD

**Issue by nigel12341** [discordjs/opus#120]
npm WARN deprecated discord-api-types@0.22.0: No longer supported. Install the latest release!
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\ffmpeg-static',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\ffmpeg-static'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\ffmpeg-static'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\ffmpeg-static',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\ffmpeg-static'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\ffmpeg-static'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR! cl : Command line warning D9002: ignoring unknown option '/Zc:__cplusplus' [C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\build\deps\libopus.vcxproj]
npm ERR! cl : Command line warning D9002: ignoring unknown option '-std:c++17' [C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\build\deps\libopus.vcxproj]
npm ERR!   opus_multistream.c
npm ERR! c:\users\nigel\onedrive\software\code\discord-bots\dijkendamdiscordbot\node_modules\@discordjs\opus\deps\opus\celt\entenc.h(30): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory [C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\build\deps\libopus.vcxproj]
npm ERR! Failed to execute 'C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\node\bin\node.exe C:\Users\nigel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown\opus.node --module_name=opus --module_path=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.4.2
npm ERR! node-pre-gyp info using node@17.4.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown\opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v102-napi-v3-win32-x64-unknown-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v102-napi-v3-win32-x64-unknown-unknown.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.6.0 and node@17.4.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.6.0/opus-v0.6.0-node-v102-napi-v3-win32-x64-unknown-unknown.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.3 found at "C:\Users\nigel\AppData\Local\Programs\Python\Python38\python.exe"
npm ERR! gyp info find VS using VS2015 (14.0) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\nigel\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\AppData\\Local\\node-gyp\\Cache\\17.4.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nigel\\AppData\\Local\\node-gyp\\Cache\\17.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\nigel\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\nigel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\node\\bin\\node.exe" "C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\prebuild\\node-v102-napi-v3-win32-x64-unknown-unknown\\opus.node" "--module_name=opus" "--module_path=C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\prebuild\\node-v102-napi-v3-win32-x64-unknown-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus
npm ERR! gyp ERR! node -v v17.4.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\node\bin\node.exe C:\Users\nigel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown\opus.node --module_name=opus --module_path=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\node-pre-gyp\lib\util\compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22000
npm ERR! node-pre-gyp ERR! command "C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\node\\bin\\node.exe" "C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus
npm ERR! node-pre-gyp ERR! node -v v17.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.2
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nigel\AppData\Local\npm-cache\_logs\2022-02-16T23_14_36_364Z-debug-0.log
PS C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot> npm install @discordjs/opus
npm ERR! code 1
npm ERR! path C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
npm ERR! cl : Command line warning D9002: ignoring unknown option '/Zc:__cplusplus' [C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\build\deps\libopus.vcxproj]
npm ERR! cl : Command line warning D9002: ignoring unknown option '-std:c++17' [C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\build\deps\libopus.vcxproj]
npm ERR!   opus_multistream.c
npm ERR! c:\users\nigel\onedrive\software\code\discord-bots\dijkendamdiscordbot\node_modules\@discordjs\opus\deps\opus\celt\entenc.h(30): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory [C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\build\deps\libopus.vcxproj]
npm ERR! Failed to execute 'C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\node\bin\node.exe C:\Users\nigel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown\opus.node --module_name=opus --module_path=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.4.2
npm ERR! node-pre-gyp info using node@17.4.0 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown\opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v102-napi-v3-win32-x64-unknown-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v102-napi-v3-win32-x64-unknown-unknown.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.7.0 and node@17.4.0 (node-v102 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.7.0/opus-v0.7.0-node-v102-napi-v3-win32-x64-unknown-unknown.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.8.3 found at "C:\Users\nigel\AppData\Local\Programs\Python\Python38\python.exe"
npm ERR! gyp info find VS using VS2015 (14.0) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\nigel\AppData\Local\Programs\Python\Python38\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\AppData\\Local\\node-gyp\\Cache\\17.4.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\nigel\\AppData\\Local\\node-gyp\\Cache\\17.4.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\nigel\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@17.4.0 | win32 | x64
npm ERR! gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\nigel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\node\\bin\\node.exe" "C:\\Users\\nigel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\prebuild\\node-v102-napi-v3-win32-x64-unknown-unknown\\opus.node" "--module_name=opus" "--module_path=C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\opus\\prebuild\\node-v102-napi-v3-win32-x64-unknown-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus
npm ERR! gyp ERR! node -v v17.4.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\node\bin\node.exe C:\Users\nigel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown\opus.node --module_name=opus --module_path=C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus\prebuild\node-v102-napi-v3-win32-x64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\node-pre-gyp\lib\util\compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22000
npm ERR! node-pre-gyp ERR! command "C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\node\\bin\\node.exe" "C:\\Users\\nigel\\OneDrive\\Software\\Code\\Discord-Bots\\DijkendamDiscordBot\\node_modules\\@discordjs\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd C:\Users\nigel\OneDrive\Software\Code\Discord-Bots\DijkendamDiscordBot\node_modules\@discordjs\opus
npm ERR! node-pre-gyp ERR! node -v v17.4.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.2
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nigel\AppData\Local\npm-cache\_logs\2022-02-16T23_17_36_750Z-debug-0.log

**Comment by VlaDexa** [comment]
Your MSBuild returned a non-zero exit code, which means it failed to build libopus library
