### ISSUE TITLE
Old GLIBC_2.29 dependency crashes Opus

### ISSUE THREAD

**Issue by isolin** [discordjs/opus#13]
I am not able to play music, since after calling `play` on a voice channel I get:

```
(node:12145) UnhandledPromiseRejectionWarning: Error: Could not find an Opus module! Please install @discordjs/opus, node-opus, or opusscript.
    at new OpusStream (/home/user/DiscordBot/node_modules/prism-media/src/opus/Opus.js:42:13)
    at new Encoder (/home/user/DiscordBot/node_modules/prism-media/src/opus/Opus.js:130:5)
    at AudioPlayer.playPCMStream (/home/user/DiscordBot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (/home/user/DiscordBot/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
    at VoiceConnection.play (/home/user/DiscordBot/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
    at play (/home/user/DiscordBot/index.js:10:29)
    at targetChannel.join.then.connection (/home/user/DiscordBot/index.js:39:61)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:12145) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I examined that closer by starting `node` and calling `require("@discordjs/opus")` with the following result:
```
Error: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/user/DiscordBot/node_modules/@discordjs/opus/prebuild/node-v67-linux-x64-glibc/opus.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

I am at Ubuntu Focal Fossa, having `libc6` installed... however it's version 2.31. This is quite awkward. How to deal with that / shouldn't it be fixed?

**Comment by isolin** [comment]
Would be great :)

**Comment by iCrawl** [comment]
I have some good news and some bad news:

Good news: We include the glibc version in the check now.
Bad news: We are probably not going to build against newer glibc versions that aren't included in the github runners yet, BUT it should now properly build itself after detecting that there isn't a proper download for that glibc version

**Comment by BaybaraEvgeny** [comment]
@isolin did you make it work?
@iCrawl I'm getting the same error and I can't find the solution!

**Comment by iCrawl** [comment]
Can you post the full error you are getting?

**Comment by BaybaraEvgeny** [comment]
@iCrawl 
`(node:136162) UnhandledPromiseRejectionWarning: Error: Error: /snap/core/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.32/opus.node)
Error: Cannot find module 'node-opus'
Require stack:
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/util/loader.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/opus/Opus.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/opus/index.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/index.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/Client.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/index.js
- /home/baybara/WebstormProjects/discord-voice-recorder/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/util/loader.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/opus/Opus.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/opus/index.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/index.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/player/BasePlayer.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/VoiceBroadcast.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/ClientVoiceManager.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/Client.js
- /home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/index.js
- /home/baybara/WebstormProjects/discord-voice-recorder/index.js
    at Object.loader [as require] (/home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/baybara/WebstormProjects/discord-voice-recorder/node_modules/prism-media/src/opus/Opus.js:135:5)
    at AudioPlayer.playPCMStream (/home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/player/BasePlayer.js:58:34)
    at AudioPlayer.playUnknown (/home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/player/BasePlayer.js:53:17)
    at VoiceConnection.play (/home/baybara/WebstormProjects/discord-voice-recorder/node_modules/discord.js/src/client/voice/util/PlayInterface.js:71:28)
    at /home/baybara/WebstormProjects/discord-voice-recorder/bin/commands.js:18:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:136162) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:136162) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by iCrawl** [comment]
We don't even build for GLIBC 2.32, so something must be messed up with your system dependencies.

**Comment by BaybaraEvgeny** [comment]
@iCrawl what system dependencies? You mean node.js is messed up? Or something else?

**Comment by BaybaraEvgeny** [comment]
@iCrawl 
`Uncaught (in promise) Error: Error: Cannot find module '/home/baybara/WebstormProjects/electronApp/packages/opus/prebuild/electron-v12.0-napi-v3-linux-x64-glibc-2.32/opus.node'
Require stack:
- /home/baybara/WebstormProjects/electronApp/packages/opus/lib/index.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/util/loader.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/opus/Opus.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/opus/index.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/index.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/player/BasePlayer.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/VoiceBroadcast.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/ClientVoiceManager.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/Client.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/index.js
- /home/baybara/WebstormProjects/electronApp/index.html
Error: Loading non-context-aware native module in renderer: '/home/baybara/WebstormProjects/electronApp/node_modules/node-opus/build/Release/node-opus.node', but app.allowRendererProcessReuse is true. See https://github.com/electron/electron/issues/18397.
Error: Cannot find module 'opusscript'
Require stack:
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/util/loader.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/opus/Opus.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/opus/index.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/index.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/player/BasePlayer.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/player/BroadcastAudioPlayer.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/VoiceBroadcast.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/ClientVoiceManager.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/Client.js
- /home/baybara/WebstormProjects/electronApp/packages/discord.js/src/index.js
- /home/baybara/WebstormProjects/electronApp/index.html
    at Object.loader [as require] (/home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/util/loader.js:12)
    at loadOpus (/home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/opus/Opus.js:17)
    at new OpusStream (/home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/opus/Opus.js:46)
    at new Encoder (/home/baybara/WebstormProjects/electronApp/packages/discord.js/node_modules/prism-media/src/opus/Opus.js:135)
    at AudioPlayer.playPCMStream (/home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/player/BasePlayer.js:58)
    at AudioPlayer.playUnknown (/home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/player/BasePlayer.js:53)
    at VoiceConnection.play (/home/baybara/WebstormProjects/electronApp/packages/discord.js/src/client/voice/util/PlayInterface.js:71)
    at Client.<anonymous> (index.html:70)`
