### ISSUE TITLE
NPM install fails on ec2 server

### ISSUE THREAD

**Issue by SebastianRefsnes** [discordjs/opus#21]
Hey! Trying to install setup a project using an AWS ec2 server. It seems that there are some errors with opus? Any idea on how to fix this? 

```
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

> @discordjs/opus@0.2.1 install /home/ec2-user/progra/cosmos/node_modules/@discordjs/opus
> patch-package && node-pre-gyp install --fallback-to-build

patch-package 6.2.2
Applying patches...
Error: Patch file found for package node-pre-gyp which is not present at node_modules/node-pre-gyp
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.2.1/opus-v0.2.1-node-v48-linux-x64-glibc.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.2.1 and node@6.17.1 (node-v48 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory `/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/build'
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
make: cc: Command not found
make: *** [Release/obj.target/libopus/deps/opus/src/opus_multistream.o] Error 127
make: Leaving directory `/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules.bundled/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.14.173-137.229.amzn2.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/prebuild/node-v48-linux-x64-glibc/opus.node" "--module_name=opus" "--module_path=/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/prebuild/node-v48-linux-x64-glibc" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v48"
gyp ERR! cwd /home/ec2-user/progra/cosmos/node_modules/@discordjs/opus
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/prebuild/node-v48-linux-x64-glibc/opus.node --module_name=opus --module_path=/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/prebuild/node-v48-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v48' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ec2-user/progra/cosmos/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Linux 4.14.173-137.229.amzn2.x86_64
node-pre-gyp ERR! command "/usr/bin/node" "/home/ec2-user/progra/cosmos/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ec2-user/progra/cosmos/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v6.17.1
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/prebuild/node-v48-linux-x64-glibc/opus.node --module_name=opus --module_path=/home/ec2-user/progra/cosmos/node_modules/@discordjs/opus/prebuild/node-v48-linux-x64-glibc --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v48' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN discord.js@12.2.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN discord.js@12.2.0 requires a peer of erlpack@discordapp/erlpack but none was installed.
npm WARN discord.js@12.2.0 requires a peer of libsodium-wrappers@^0.7.6 but none was installed.
npm WARN discord.js@12.2.0 requires a peer of sodium@^3.0.2 but none was installed.
npm WARN discord.js@12.2.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm WARN discord.js@12.2.0 requires a peer of zlib-sync@^0.1.6 but none was installed.
npm WARN prism-media@1.2.2 requires a peer of ffmpeg-static@^2.4.0 || ^3.0.0 but none was installed.
npm WARN prism-media@1.2.2 requires a peer of @discordjs/opus@^0.1.0 but none was installed.
npm WARN prism-media@1.2.2 requires a peer of node-opus@^0.3.1 but none was installed.
npm WARN prism-media@1.2.2 requires a peer of opusscript@^0.0.6 but none was installed.
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm ERR! Linux 4.14.173-137.229.amzn2.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "--unsafe-perm"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! @discordjs/opus@0.2.1 install: `patch-package && node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.2.1 install script 'patch-package && node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @discordjs/opus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     patch-package && node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @discordjs/opus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @discordjs/opus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/progra/cosmos/npm-debug.log
```

**Comment by iCrawl** [comment]
What OS is this running?

**Comment by SebastianRefsnes** [comment]
> What OS is this running?

It's running "Amazon linux"
![image](https://user-images.githubusercontent.com/22845479/82492583-bea71d00-9ae6-11ea-8c66-24f49d8d533d.png)

**Comment by iCrawl** [comment]
Based on centOS, okay.

Looks like it doesn't have build tools installed.

Try something like `sudo yum groupinstall 'Development Tools'` or `sudo yum install gcc gcc-c++ make`

**Comment by SebastianRefsnes** [comment]
> Based on centOS, okay.
> 
> Looks like it doesn't have build tools installed.
> 
> Try something like `sudo yum groupinstall 'Development Tools'` or `sudo yum install gcc gcc-c++ make`

Look's like that did the trick, thanks!
