### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by SoulHarsh007** [discordjs/opus#22]
Fails on install script nodejs v: 14.3.0 npm v: 6.14.5 

I also attempted to install with pnpm (v4.14.4) results into same error.

```
g++: error: Music/node_modules/node-addon-api: No such file or directory
make: *** [opus.target.mk:158: Release/obj.target/opus/src/node-opus.o] Error 1
make: Leaving directory '/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.4.0-31-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31/opus.node" "--module_name=opus" "--module_path=/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus
gyp ERR! node -v v14.3.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 5.4.0-31-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/harsh-peshwani/Desktop/Saki Music/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v14.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/home/harsh-peshwani/Desktop/Saki Music/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN saki-music@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/harsh-peshwani/.npm/_logs/2020-05-27T08_13_23_389Z-debug.log
```

**Further details:**

- @discordjs/opus version: 0.3.2
- Node.js version: 14.4.0
- Operating system: Ubuntu 20.04 (x64)
- Priority this issue should have – please be realistic and elaborate if possible: Normal

**Comment by iCrawl** [comment]
https://github.com/discordjs/opus/issues/21#issuecomment-631701450

If you aren't running centOS, find the equivalent to this based on your OS.

**Comment by SoulHarsh007** [comment]
I have build tools installed correctly

**Comment by iCrawl** [comment]
Well you apparently do not have `make` installed, which is an essential build tool.

**Comment by SoulHarsh007** [comment]
I was able to use this package previously (including older versions) on same os

**Comment by iCrawl** [comment]
I don't know what else to tell you but you do not have the correct build tools installed.

https://packages.ubuntu.com/groovy/build-essential

**Comment by SoulHarsh007** [comment]
Already installed

**Comment by SoulHarsh007** [comment]
> Well you apparently do not have `make` installed, which is an essential build tool.

```
make is already the newest version (4.2.1-1.2).
make set to manually installed.
```
This shows up when I attempt to install `make` therefore it's already installed

**Comment by iCrawl** [comment]
I just set up a new droplet on DO with 20.04 x64

```
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
$ nvm install 14
$ apt install build-essential

---

$ node -v
v14.3.0
$ npm -v
> 6.14.5
$ make -v
> GNU Make 4.2.1
> Built for x86_64-pc-linux-gnu
$ python3
> Python 3.8.2 (default, Apr 27 2020, 15:53:34)
> [GCC 9.3.0] on linux
$ gcc -v
> gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)
```

![image](https://user-images.githubusercontent.com/20760160/82997556-ceeb5a80-a006-11ea-87fb-56793de4f94b.png)

**Comment by SoulHarsh007** [comment]
Nodejs v: 14.3.0
npm v: 6.14.5
make v: GNU Make 4.2.1
python v: Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
gcc v: gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2) 
Same versions but still not able to install

**Comment by iCrawl** [comment]
Well that means something is most likely wrong with your OS or missing some tools.

I just showed you how on a completely new droplet it just works fine so its most likely not an issue with the library.

**Comment by SoulHarsh007** [comment]
I was able to install the package!
The problem was the folder name it had white spaces!
I attempted to install the same package in my test folder and it was successful, then I renamed my folder from `Saki Music` to `saki-music` and was able to install the package!
