### ISSUE TITLE
Install issues on WSL2

### ISSUE THREAD

**Issue by mzguimaraes** [discordjs/opus#25]
**Please describe the problem you are having in as much detail as possible:**

This package fails to install via npm on my WSL2 Ubuntu installation.  See output below.

This is only the second project I've done on this install, so the environment should be relatively pristine.  Not an expert at Linux so if you need more information about it please let me know what to run :)

Looking at the output, it seems like there are two issues present:
* The URL npm is using for the pre-built binary install 404s.  Looking at the packages in release v0.3.2, there isn't a binary released for glibc 2.3, the version current WSL2 Ubuntu ships with.
  * URL: https://github.com/discordjs/opus/releases/download/v0.3.2/opus-v0.3.2-node-v72-napi-v3-linux-x64-glibc-2.31.tar.gz
* npm then falls back to building from source, but `node-pre-gyp` fails at some point during the process.  Looks like this is related to the fix in release v0.3.2?

**Include a reproducible code sample here, if possible:**
```
marcus@Longclaw:/mnt/c/Users/Marcus/programming/music-bot$ sudo npm i --save @discordjs/opus

> @discordjs/opus@0.3.2 install /mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.2/opus-v0.3.2-node-v72-napi-v3-linux-x64-glibc-2.31.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.2 and node@12.18.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
gyp WARN EACCES current user ("marcus") does not have permission to access the dev dir "/root/.cache/node-gyp/12.18.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/.node-gyp"
make: Entering directory '/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/build'
make: *** No rule to make target '../.node-gyp/12.18.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.31/opus.node" "--module_name=opus" "--module_path=/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.31" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.31 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/usr/local/bin/node" "/mnt/c/Users/Marcus/programming/music-bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v12.18.0
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/mnt/c/Users/Marcus/programming/music-bot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.31 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN music-bot@1.0.0 No description
npm WARN music-bot@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-15T01_46_32_274Z-debug.log
```
**Further details:**

- @discordjs/opus version:
- Node.js version: v12.18.0
- Operating system: Linux 4.4.0-18362-Microsoft (WSL2 Ubuntu)
- Priority this issue should have – please be realistic and elaborate if possible: 
  - Medium, build fails on relatively common OS configuration

**Comment by vladfrangu** [comment]
Don't..use sudo..

**Comment by mzguimaraes** [comment]
...I could've sworn I'd tried it both ways.  Little embarrassed now.  Thanks @vladfrangu.

It still doesn't build, but it gets further in the process.  Looks like there's an issue with node-pre-gyp now, I'll follow up with them.

**Comment by vladfrangu** [comment]
Could you provide the error you're still getting? Maybe something broke? Cause I just tried it on WSL2 on nodejs 14 iirc and it worked just fine 👀
