### ISSUE TITLE
Package fails to build on one machine but seems to work fine on another. (both Windows with WSL2)

### ISSUE THREAD

**Issue by chevtek** [discordjs/opus#32]
**Please describe the problem you are having in as much detail as possible:** I have a Discord bot I'm working on. I have a windows 10 Desktop PC running WSL 2 (Ubuntu) and that is where I've installed @discordjs/opus. On my desktop machine this worked just fine with no issues. I checked out my project on my laptop with the same setup and I get an error when trying to `npm install @discordjs/opus`.

```
chev@C100003373:~/code/chevbot$ npm install @discordjs/opus

> @discordjs/opus@0.3.2 install /home/chev/code/chevbot/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.2/opus-v0.3.2-node-v79-napi-v3-linux-x64-glibc-2.31.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.2 and node@13.3.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/home/chev/code/chevbot/node_modules/@discordjs/opus/build'
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/analysis.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp_data.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_projection_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mapping_matrix.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_compare.o
  CC(target) Release/obj.target/libopus/deps/opus/src/mlp.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/src/repacketizer.o
  CC(target) Release/obj.target/libopus/deps/opus/src/opus_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_frame.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/inner_product_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/scale_vector_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_pred_coefs_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/schur_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/warped_autocorrelation_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/burg_modified_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_LPC_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LPC_inv_pred_gain_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/scale_copy_vector_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/noise_shape_analysis_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/pitch_analysis_core_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/bwexpander_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LTP_analysis_filter_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LTP_scale_ctrl_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/corrMatrix_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/encode_frame_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/sort_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_pitch_lags_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/residual_energy_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/LPC_analysis_filter_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/autocorrelation_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/k2a_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/regularize_correlations_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/find_LTP_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/energy_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/apply_sine_window_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/wrappers_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/float/process_gains_FLP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_quant_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_inv_pred_gain.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/process_NLSFs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NSQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/check_control_input.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_del_dec_quant.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_analysis_filter.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/dec_API.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sort.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/VAD.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_AR2.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LPC_fit.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_SNR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_parameters.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/pitch_est_tables.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/warped_autocorrelation_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/apply_sine_window_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/residual_energy16_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/schur64_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/residual_energy_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/noise_shape_analysis_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/encode_frame_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/schur_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/autocorr_FIX.o
../deps/opus/silk/fixed/autocorr_FIX.c: In function ‘silk_autocorr’:
../deps/opus/silk/fixed/autocorr_FIX.c:47:29: warning: passing argument 1 of ‘_celt_autocorr’ from incompatible pointer type [-Wincompatible-pointer-types]
   47 |     *scale = _celt_autocorr(inputData, results, NULL, 0, corrCount-1, inputDataSize, arch);
      |                             ^~~~~~~~~
      |                             |
      |                             const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/autocorr_FIX.c:33:
../deps/opus/celt/celt_lpc.h:63:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
   63 | int _celt_autocorr(const opus_val16 *x, opus_val32 *ac,
      |                    ~~~~~~~~~~~~~~~~~~^
../deps/opus/silk/fixed/autocorr_FIX.c:47:40: warning: passing argument 2 of ‘_celt_autocorr’ from incompatible pointer type [-Wincompatible-pointer-types]
   47 |     *scale = _celt_autocorr(inputData, results, NULL, 0, corrCount-1, inputDataSize, arch);
      |                                        ^~~~~~~
      |                                        |
      |                                        opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/autocorr_FIX.c:33:
../deps/opus/celt/celt_lpc.h:63:53: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
   63 | int _celt_autocorr(const opus_val16 *x, opus_val32 *ac,
      |                                         ~~~~~~~~~~~~^~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/burg_modified_FIX.o
../deps/opus/silk/fixed/burg_modified_FIX.c: In function ‘silk_burg_modified_c’:
../deps/opus/silk/fixed/burg_modified_FIX.c:98:30: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                              ^~~~~
      |                              |
      |                              const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/burg_modified_FIX.c:98:43: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                                     ~~~~~~^~~
      |                                           |
      |                                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/burg_modified_FIX.c:98:48: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
   98 |             celt_pitch_xcorr(x_ptr, x_ptr + 1, xcorr, subfr_length - D, D, arch );
      |                                                ^~~~~
      |                                                |
      |                                                opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/burg_modified_FIX.c:35:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/pitch_analysis_core_FIX.o
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c: In function ‘silk_pitch_analysis_core’:
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:27: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                           ^~~~~~~~~~
      |                           |
      |                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:50: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                                                  ^
      |                                                  |
      |                                                  const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:200:66: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  200 |         celt_pitch_xcorr( target_ptr, target_ptr - MAX_LAG_4KHZ, xcorr32, SF_LENGTH_8KHZ, MAX_LAG_4KHZ - MIN_LAG_4KHZ + 1, arch );
      |                                                                  ^~~~~~~
      |                                                                  |
      |                                                                  opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c: In function ‘silk_P_Ana_calc_corr_st3’:
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:27: warning: passing argument 1 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                           ^~~~~~~~~~
      |                           |
      |                           const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:38: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                    ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:62: warning: passing argument 2 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                                       ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                                              |
      |                                                              const opus_int16 * {aka const short int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:185:60: note: expected ‘const opus_val16 *’ {aka ‘const float *’} but argument is of type ‘const opus_int16 *’ {aka ‘const short int *’}
  185 | celt_pitch_xcorr_c(const opus_val16 *_x, const opus_val16 *_y,
      |                                          ~~~~~~~~~~~~~~~~~~^~
../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:616:74: warning: passing argument 3 of ‘celt_pitch_xcorr_c’ from incompatible pointer type [-Wincompatible-pointer-types]
  616 |         celt_pitch_xcorr( target_ptr, target_ptr - start_lag - lag_high, xcorr32, sf_length, lag_high - lag_low + 1, arch );
      |                                                                          ^~~~~~~
      |                                                                          |
      |                                                                          opus_int32 * {aka int *}
In file included from ../deps/opus/silk/fixed/pitch_analysis_core_FIX.c:39:
../deps/opus/celt/pitch.h:186:19: note: expected ‘opus_val32 *’ {aka ‘float *’} but argument is of type ‘opus_int32 *’ {aka ‘int *’}
  186 |       opus_val32 *xcorr, int len, int max_pitch, int arch);
      |       ~~~~~~~~~~~~^~~~~
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_LTP_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_LPC_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/corrMatrix_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/k2a_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/LTP_scale_ctrl_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/process_gains_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/k2a_Q16_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/regularize_correlations_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/LTP_analysis_filter_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/vector_ops_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_pitch_lags_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/fixed/find_pred_coefs_FIX.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_audio_bandwidth.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decoder_set_fs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_unpack.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/bwexpander.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_rom.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/shell_coder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_pulses.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/bwexpander_32.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_core.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/PLC.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_NLSF_CB_WB.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/table_LSF_cos.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_pulses_per_block.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_gain.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/inner_prod_aligned.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_down2_3.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NSQ_del_dec.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_pitch.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_VQ_weights_laroia.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/interpolate.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/debug.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_other.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/LP_variable_cutoff.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_decode.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/encode_pulses.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/control_codec.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_LR_to_MS.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/HP_variable_cutoff.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/encode_indices.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/init_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_encode_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_VQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/init_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_IIR_FIR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_up2_HQ.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sigm_Q15.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/sum_sqr_shift.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_LTP.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_down2.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/code_signs.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_NLSF_CB_NB_MB.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/gain_quant.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/tables_pitch_lag.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_stabilize.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_find_predictor.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/A2NLSF.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF2A.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/VQ_WMat_EC.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/NLSF_encode.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/log2lin.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_decode_pred.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/lin2log.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/CNG.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/enc_API.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/biquad_alt.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/quant_LTP_gains.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/resampler_private_down_FIR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/ana_filt_bank_1.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/stereo_MS_to_LR.o
  CC(target) Release/obj.target/libopus/deps/opus/silk/decode_indices.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/rate.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entdec.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/modes.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_lpc.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/laplace.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/cwrs.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entcode.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_decoder.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/celt_encoder.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/mdct.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/quant_bands.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/vq.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/bands.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/kiss_fft.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/entenc.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/mathops.o
  CC(target) Release/obj.target/libopus/deps/opus/celt/pitch.o
  AR(target) Release/obj.target/deps/opus.a
  COPY Release/opus.a
  CXX(target) Release/obj.target/opus/src/node-opus.o
make: g++: Command not found
make: *** [opus.target.mk:156: Release/obj.target/opus/src/node-opus.o] Error 127
make: Leaving directory '/home/chev/code/chevbot/node_modules/@discordjs/opus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/chev/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
gyp ERR! System Linux 4.19.104-microsoft-standard
gyp ERR! command "/home/chev/.nvm/versions/node/v13.3.0/bin/node" "/home/chev/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/chev/code/chevbot/node_modules/@discordjs/opus/prebuild/node-v79-napi-v3-linux-x64-glibc-2.31/opus.node" "--module_name=opus" "--module_path=/home/chev/code/chevbot/node_modules/@discordjs/opus/prebuild/node-v79-napi-v3-linux-x64-glibc-2.31" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/chev/code/chevbot/node_modules/@discordjs/opus
gyp ERR! node -v v13.3.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/chev/.nvm/versions/node/v13.3.0/bin/node /home/chev/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/chev/code/chevbot/node_modules/@discordjs/opus/prebuild/node-v79-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/home/chev/code/chevbot/node_modules/@discordjs/opus/prebuild/node-v79-napi-v3-linux-x64-glibc-2.31 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/chev/code/chevbot/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:219:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1027:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:5)
node-pre-gyp ERR! System Linux 4.19.104-microsoft-standard
node-pre-gyp ERR! command "/home/chev/.nvm/versions/node/v13.3.0/bin/node" "/home/chev/code/chevbot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/chev/code/chevbot/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v13.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok
Failed to execute '/home/chev/.nvm/versions/node/v13.3.0/bin/node /home/chev/.nvm/versions/node/v13.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/chev/code/chevbot/node_modules/@discordjs/opus/prebuild/node-v79-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/home/chev/code/chevbot/node_modules/@discordjs/opus/prebuild/node-v79-napi-v3-linux-x64-glibc-2.31 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN chevbot@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chev/.npm/_logs/2020-07-30T03_52_56_967Z-debug.log
```

Though I know node.js pretty well, when it comes to troubleshooting binary dependency building it's all Greek to me.

Full npm log in case it helps: https://gist.github.com/chevtek/32c79cd3a613213abdb6ad719d6ba2bf

**Further details:**

- @discordjs/opus version: 3.2
- Node.js version: I tried many different versions, but we'll just say the latest - v14.7.0
- Operating system: Technically Ubuntu, but it's WSL 2 on Windows.
- Priority this issue should have – please be realistic and elaborate if possible: Not urgent at all.

**Comment by iCrawl** [comment]
> make: g++: Command not found

**Comment by chevtek** [comment]
Know how I fix it? I tried to apt-get install make and that seemed to install fine but it still doesn't build

**Comment by chevtek** [comment]
Sorry, I'm a total noob with this.

**Comment by iCrawl** [comment]
This really isn't linux support.

https://stackoverflow.com/questions/13887225/make-g-command-not-found

**Comment by chevtek** [comment]
Okay, you don't have to be a smart ass. Thanks anyway.
