### ISSUE TITLE
Could not convert AAC to OPUS

### ISSUE THREAD

**Issue by pavel-luhin** [discordjs/opus#38]
Hi. I am trying to convert aac file to opus file using this library. As I found, first of all I have to decode this from aac to `Buffer` and then encode with `@discordjs/opus`.

```js
var AV = require('av');
require('aac');

const { OpusEncoder } = require('@discordjs/opus');
const encoder = new OpusEncoder(48000, 2);

var toBuffer = require('typedarray-to-buffer');

const createBuffer = require('audio-buffer-from');

const doConvert = async () => {
    const fileAddr = '/Users/pluhin/Downloads/1599913142871.aac';
    var asset = AV.Asset.fromFile(fileAddr);

    asset.on('buffer', percent => console.log("Loading audio file... %d%", percent));
    asset.on('decodeStart', () => console.log("Audio decoding started."));
    asset.on('error', err => console.log("Audio processing failed: %o", err));

    await asset.decodeToBuffer(buffer =>  {
        const encoded = encoder.encode(buffer);
        console.log('123');
    });


    asset.start();
}

doConvert();
```

- @discordjs/opus version: ^0.3.2
- Node.js version: v14.10.1
- Operating system: macOs

This is my log. As I see, error in callback function, that means that error in encoder, but encoder didn't throw any error.

```
> test-convert-audio@1.0.0 start /Users/pluhin/projects/anyvoice/test-convert-audio
> npx ts-node test.ts

Loading audio file... 61.099560884198354%
Loading audio file... 100%
Audio decoding started.

/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/asset.js:126
        return callback(buf);
               ^
Error: Unknown failure
    at /Users/pluhin/projects/anyvoice/test-convert-audio/test.ts:21:33
    at Asset.<anonymous> (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/asset.js:126:16)
    at Asset.cb (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/core/events.js:51:19)
    at Asset.EventEmitter.emit (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/core/events.js:64:12)
    at Class.<anonymous> (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/asset.js:202:24)
    at Class.EventEmitter.emit (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/core/events.js:64:12)
    at Class.Decoder.decode (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/decoder.js:90:14)
    at Class.<anonymous> (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/decoder.js:54:26)
    at Class.EventEmitter.emit (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/core/events.js:64:12)
    at FileSource.<anonymous> (/Users/pluhin/projects/anyvoice/test-convert-audio/node_modules/av/src/demuxer.js:51:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-convert-audio@1.0.0 start: `npx ts-node test.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-convert-audio@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pluhin/.npm/_logs/2020-09-13T12_04_35_756Z-debug.log

Process finished with exit code 1
```

**Comment by iCrawl** [comment]
You can not just convert it to a buffer, opus needs PCM input.

**Comment by pavel-luhin** [comment]
Maybe you know how can I decode AAC to PCM?

**Comment by pavel-luhin** [comment]
I know how to get `AudioBuffer` from `aurora`. Isn't it the same as PCM?

**Comment by iCrawl** [comment]
I don't know, and we usually don't help with third party software.

FFmpeg usually can convert from X to Y with no codec restrictions.

**Comment by pavel-luhin** [comment]
Okay, thanks. Will try FFmpeg.
