### ISSUE TITLE
Opus build error

### ISSUE THREAD

**Issue by iPatavatsizz** [discordjs/opus#4]
In release page there was not a opus package for x86.
Thus is it only supports only x64 bits?
because of that am I getting errors ?

**I have all required packages, there are**;

- Node v13.12.0 (Current Version on Site, v12 tried) upgraded to v13
- Npm 6.14.4 upgraded.
- Node-gyp & pre-gyp & sass reinstalled.
- Visual Studio Community 2017 & 2019 Versions with C++ Core Features & MSBuild & NodeJS Developer Toolkit
- Python 2.7 & 3.8

**Command Prompt Output:**

> C:\Users\emre\yaurabot>npm install

> bcrypt@4.0.1 install C:\Users\emre\yaurabot\node_modules\bcrypt
> node-pre-gyp install --fallback-to-build

> node-pre-gyp WARN Using needle for node-pre-gyp https download
> [bcrypt] Success: "C:\Users\emre\yaurabot\node_modules\bcrypt\lib\binding\napi-v
> 3\bcrypt_lib.node" is installed via remote

> ffmpeg-static@4.1.1 install C:\Users\emre\yaurabot\node_modules\ffmpeg-static
> node install.js

> Error creating cache: ENOENT: no such file or directory, mkdir 'C:\Users\emre\Ap
> pData\Local\ffmpeg-static-nodejs\Cache'
> Downloading ffmpeg [||||||||||||||||||||] 100% 0.0s
> Failed to download the ffmpeg README.
> Failed to download the ffmpeg LICENSE.

> node-report@2.2.10 install C:\Users\emre\yaurabot\node_modules\node-report
> node-gyp rebuild

> C:\Users\emre\yaurabot\node_modules\node-report>if not defined npm_config_node_g
> yp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\no
> de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "
> C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js"
> rebuild )
> Bu çözümde projeler tek tek derlenir. Paralel bir derlemeyi etkinleştirmek için
> lütfen "-m" anahtarını ekleyin.
>   node_report.cc
> C:\Users\emre\yaurabot\node_modules\node-report\src\node_report.cc(1096,14): wa
> rning C4018: '<': imzalı/imzasız uyuşmazlığı [C:\Users\emre\yaurabot\node_modul
> es\node-report\build\api.vcxproj]
C:\Users\emre\yaurabot\node_modules\node-report\src\node_report.cc(1096,48): wa
> rning C4018: '<': imzalı/imzasız uyuşmazlığı [C:\Users\emre\yaurabot\node_modul
> es\node-report\build\api.vcxproj]
>   module.cc
>   utilities.cc
>   win_delay_load_hook.cc
>   Kod Üretiliyor...
 >     C:\Users\emre\yaurabot\node_modules\node-report\build\Release\api.lib kita
>   plığı ve C:\Users\emre\yaurabot\node_modules\node-report\build\Release\api.ex
 >  p nesnesi oluşturuluyor
>   api.vcxproj -> C:\Users\emre\yaurabot\node_modules\node-report\build\Release\
>   \api.node
>   Copying C:\Users\emre\yaurabot\node_modules\node-report\build\Release\/api.no
>   de to C:\Users\emre\yaurabot\node_modules\node-report\api.node
 >          1 dosya kopyalandı.
> npm notice created a lockfile as package-lock.json. You should commit this file.

> npm WARN yaurabot@1.0.0 No description
> npm WARN yaurabot@1.0.0 No repository field.

> added 216 packages from 237 contributors and audited 325 packages in 522.97s

> 7 packages are looking for funding
>   run `npm fund` for details

> found 0 vulnerabilities`

**Npm Log File (I got node-report error while installing. Therefore i tried to install only node-report > before @discord/opus)**

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   'node-report',
> 1 verbose cli   '-g'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v13.12.0
> 4 verbose npm-session a2a030ef6e860e63
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 http fetch GET 304 https://registry.npmjs.org/node-report 19386ms (from cache)
> 8 http fetch GET 200 https://registry.npmjs.org/node-report/-/node-report-2.2.10.tgz 353ms (from cache)
> 9 silly pacote tag manifest for node-report@latest fetched in 21151ms
> 10 timing stage:loadCurrentTree Completed in 21407ms
> 11 silly install loadIdealTree
> 12 silly install cloneCurrentTreeToIdealTree
> 13 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
> 14 silly install loadShrinkwrap
> 15 timing stage:loadIdealTree:loadShrinkwrap Completed in 6ms
> 16 silly install loadAllDepsIntoIdealTree
> 17 silly resolveWithNewModule node-report@2.2.10 checking installable status
> 18 http fetch GET 304 https://registry.npmjs.org/nan 345ms (from cache)
> 19 silly pacote range manifest for nan@^2.12.1 fetched in 414ms
> 20 silly resolveWithNewModule nan@2.14.0 checking installable status
> 21 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 468ms
> 22 timing stage:loadIdealTree Completed in 487ms
> 23 silly currentTree npm
> 24 silly idealTree npm
> 24 silly idealTree `-- node-report@2.2.10
> 24 silly idealTree   `-- nan@2.14.0
> 25 silly install generateActionsToTake
> 26 timing stage:generateActionsToTake Completed in 1362ms
> 27 silly diffTrees action count 2
> 28 silly diffTrees add nan@2.14.0
> 29 silly diffTrees add node-report@2.2.10
> 30 silly decomposeActions action count 16
> 31 silly decomposeActions fetch nan@2.14.0
> 32 silly decomposeActions extract nan@2.14.0
> 33 silly decomposeActions preinstall nan@2.14.0
> 34 silly decomposeActions build nan@2.14.0
> 35 silly decomposeActions install nan@2.14.0
> 36 silly decomposeActions postinstall nan@2.14.0
> 37 silly decomposeActions finalize nan@2.14.0
> 38 silly decomposeActions refresh-package-json nan@2.14.0
> 39 silly decomposeActions fetch node-report@2.2.10
> 40 silly decomposeActions extract node-report@2.2.10
> 41 silly decomposeActions preinstall node-report@2.2.10
> 42 silly decomposeActions build node-report@2.2.10
> 43 silly decomposeActions install node-report@2.2.10
> 44 silly decomposeActions postinstall node-report@2.2.10
> 45 silly decomposeActions finalize node-report@2.2.10
> 46 silly decomposeActions refresh-package-json node-report@2.2.10
> 47 silly install executeActions
> 48 silly doSerial global-install 16
> 49 verbose correctMkdir C:\Users\emre\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
> 50 verbose makeCacheDir UID & GID are irrelevant on win32
> 51 verbose lock using C:\Users\emre\AppData\Roaming\npm-cache\_locks\staging-f24761ee06b7358b.lock for C:\Users\emre\AppData\Roaming\npm\node_modules\.staging
> 52 silly doParallel extract 2
> 53 silly extract nan@2.14.0
> 54 silly extract node-report@2.2.10
> 55 silly tarball trying nan@^2.12.1 by hash: sha512-INOFj37C7k3AfaNTtX8RhsTw7qRy7eLET14cROi9+5HAVbbHuIWUHEauBv5qT4Av2tWasiTY1Jw6puUNqRJXQg==
> 56 silly tarball trying node-report@latest by hash: sha512-KANqX94qnO5MpomgNBF/r1+0OFVihwf2Ti4gu5nXne07EDtBI1Cv0xMpT29VWiUD7aJe8YtuVPP2PKapo8h2qw==
57 silly extract node-report@latest extracted to C:\Users\emre\AppData\Roaming\npm\node_modules\.staging\node-report-252dda95 (1395ms)
58 silly extract nan@^2.12.1 extracted to C:\Users\emre\AppData\Roaming\npm\node_modules\.staging\nan-16f556a7 (1707ms)
59 timing action:extract Completed in 1717ms
60 silly doReverseSerial unbuild 16
61 silly doSerial remove 16
62 silly doSerial move 16
63 silly doSerial finalize 16
64 silly finalize C:\Users\emre\AppData\Roaming\npm\node_modules\node-report\node_modules\nan
65 silly finalize C:\Users\emre\AppData\Roaming\npm\node_modules\node-report
66 timing action:finalize Completed in 108ms
67 silly doParallel refresh-package-json 2
68 silly refresh-package-json C:\Users\emre\AppData\Roaming\npm\node_modules\node-report\node_modules\nan
69 silly refresh-package-json C:\Users\emre\AppData\Roaming\npm\node_modules\node-report
70 timing action:refresh-package-json Completed in 308ms
71 silly doParallel preinstall 2
72 silly preinstall nan@2.14.0
73 info lifecycle nan@2.14.0~preinstall: nan@2.14.0
74 silly preinstall node-report@2.2.10
75 info lifecycle node-report@2.2.10~preinstall: node-report@2.2.10
76 timing action:preinstall Completed in 20ms
77 silly doSerial build 16
78 silly build nan@2.14.0
79 info linkStuff nan@2.14.0
80 silly linkStuff nan@2.14.0 has C:\Users\emre\AppData\Roaming\npm\node_modules\node-report\node_modules as its parent node_modules
81 silly linkStuff nan@2.14.0 is part of a global install
82 silly linkStuff nan@2.14.0 is installed into a global node_modules
83 silly build node-report@2.2.10
84 info linkStuff node-report@2.2.10
85 silly linkStuff node-report@2.2.10 has C:\Users\emre\AppData\Roaming\npm\node_modules as its parent node_modules
86 silly linkStuff node-report@2.2.10 is part of a global install
87 silly linkStuff node-report@2.2.10 is installed into a global node_modules
88 silly linkStuff node-report@2.2.10 is installed into the top-level global node_modules
89 timing action:build Completed in 7ms
90 silly doSerial global-link 16
91 silly doParallel update-linked 0
92 silly doSerial install 16
93 silly install nan@2.14.0
94 info lifecycle nan@2.14.0~install: nan@2.14.0
95 silly install node-report@2.2.10
96 info lifecycle node-report@2.2.10~install: node-report@2.2.10
97 verbose lifecycle node-report@2.2.10~install: unsafe-perm in lifecycle true
98 verbose lifecycle node-report@2.2.10~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\emre\AppData\Roaming\npm\node_modules\node-report\node_modules\.bin;C:\Users\emre\AppData\Roaming\npm\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Git\cmd;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\emre\.windows-build-tools\python27\;C:\Users\emre\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\emre\AppData\Local\Programs\Python\Python38-32\;C:\Users\emre\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\emre\AppData\Local\Yarn\bin;C:\Users\emre\AppData\Roaming\npm
99 verbose lifecycle node-report@2.2.10~install: CWD: C:\Users\emre\AppData\Roaming\npm\node_modules\node-report
100 silly lifecycle node-report@2.2.10~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
101 silly lifecycle node-report@2.2.10~install: Returned: code: 1  signal: null
102 info lifecycle node-report@2.2.10~install: Failed to exec install script
103 timing action:install Completed in 572ms
104 verbose unlock done using C:\Users\emre\AppData\Roaming\npm-cache\_locks\staging-f24761ee06b7358b.lock for C:\Users\emre\AppData\Roaming\npm\node_modules\.staging
105 timing stage:rollbackFailedOptional Completed in 213ms
106 timing stage:runTopLevelLifecycles Completed in 26254ms
107 verbose stack Error: node-report@2.2.10 install: `node-gyp rebuild`
107 verbose stack Exit status 1
107 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
107 verbose stack     at EventEmitter.emit (events.js:315:20)
107 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
107 verbose stack     at ChildProcess.emit (events.js:315:20)
107 verbose stack     at maybeClose (internal/child_process.js:1026:16)
107 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
108 verbose pkgid node-report@2.2.10
109 verbose cwd C:\Users\emre\yaurabot
110 verbose Windows_NT 6.1.7601
111 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-report" "-g"
112 verbose node v13.12.0
113 verbose npm  v6.14.4
114 error code ELIFECYCLE
115 error errno 1
116 error node-report@2.2.10 install: `node-gyp rebuild`
116 error Exit status 1
117 error Failed at the node-report@2.2.10 install script.
117 error This is probably not a problem with npm. There is likely additional logging output above.
118 verbose exit [ 1, true ]

`

Sorry for bad English and syntax errors...

**Comment by iPatavatsizz** [comment]
Hello? There is a helper(!)
