### ISSUE TITLE
Cannot install the package on Debian 9

### ISSUE THREAD

**Issue by KrisTheNewest** [discordjs/opus#42]
```
root@closure:/home/myname/myfolder# npm i @discordjs/opus@0.2.0

> @discordjs/opus@0.2.0 install /home/myname/myfolder/node_modules/@discordjs/opus
> patch-package && node-pre-gyp install --fallback-to-build

sh: 1: patch-package: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @discordjs/opus@0.2.0 install: `patch-package && node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-22T09_45_10_936Z-debug.log
```
- @discordjs/opus version: 0.3.2 (happens on any version though it seems)
- Node.js version: v12.19.0
- Operating system: Debian 9.13
Works fine on Windows 10 and Debian 10 though. I tried to install the dependencies myself, nothing has changed.

**Comment by iCrawl** [comment]
> > @discordjs/opus@0.2.0 install /home/myname/myfolder/node_modules/@discordjs/opus

> @discordjs/opus version: 0.3.2 (happens on any version though it seems)

Something doesn't add up here.

**Comment by KrisTheNewest** [comment]
> > > @discordjs/opus@0.2.0 install /home/myname/myfolder/node_modules/@discordjs/opus
> 
> > @discordjs/opus version: 0.3.2 (happens on any version though it seems)
> 
> Something doesn't add up here.

Yeah, sorry about that, i get the same/very similar problem on any version of the library, that's why I added that part.

**Comment by iCrawl** [comment]
Similar is not the same, the error messages differ. `patch-package` is not even used anymore, so I can't give any help or hints into a certain direction if I don't know the error message on the latest version.

**Comment by KrisTheNewest** [comment]
@iCrawl Sorry about that, I should have been more clear. Here's the full error from the terminal, I attached the log file from the error as well.
```
krissthenewest@closure:~/MayerBot$ npm install @discordjs/opus

> @discordjs/opus@0.3.3 install /home/krissthenewest/MayerBot/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v72-napi-v3-linux-x64-glibc-2.24.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.3 and node@12.19.0 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
gyp ERR! System Linux 4.9.0-13-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/krissthenewest/MayerBot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.24/opus.node" "--module_name=opus" "--module_path=/home/krissthenewest/MayerBot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.24" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/krissthenewest/MayerBot/node_modules/@discordjs/opus
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/krissthenewest/MayerBot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.24/opus.node --module_name=opus --module_path=/home/krissthenewest/MayerBot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.24 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/krissthenewest/MayerBot/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.9.0-13-amd64
node-pre-gyp ERR! command "/usr/bin/node" "/home/krissthenewest/MayerBot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/krissthenewest/MayerBot/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v12.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/krissthenewest/MayerBot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.24/opus.node --module_name=opus --module_path=/home/krissthenewest/MayerBot/node_modules/@discordjs/opus/prebuild/node-v72-napi-v3-linux-x64-glibc-2.24 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.3.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/krissthenewest/.npm/_logs/2020-10-26T11_13_52_141Z-debug.log
```
[2020-10-26T11_13_52_141Z-debug.log](https://github.com/discordjs/opus/files/5438434/2020-10-26T11_13_52_141Z-debug.log)

**Comment by iCrawl** [comment]
Well then, make sure you have build tools installed on your linux environment

https://github.com/discordjs/opus/issues/43#issuecomment-716168497

**Comment by KrisTheNewest** [comment]
A lot of text popped up, including some warnings but everything works just fine, thanks a lot!
