### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by FredTheNoob** [discordjs/opus#43]
**Please describe the problem you are having in as much detail as possible:**
When I run npm i @discordjs/opus I get a build error:

**Include a reproducible code sample here, if possible:**

```js
npm i @discordjs/opus

> @discordjs/opus@0.3.2 install /home/fred/Wavynn/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.2/opus-v0.3.2-node-v83-napi-v3-linux-x64-glibc-2.31.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.2 and node@14.4.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:175:21)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/home/fred/.nvm/versions/node/v14.4.0/bin/node" "/home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/fred/Wavynn/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31/opus.node" "--module_name=opus" "--module_path=/home/fred/Wavynn/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/fred/Wavynn/node_modules/@discordjs/opus
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/fred/.nvm/versions/node/v14.4.0/bin/node /home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/fred/Wavynn/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/home/fred/Wavynn/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/fred/Wavynn/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/home/fred/.nvm/versions/node/v14.4.0/bin/node" "/home/fred/Wavynn/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/fred/Wavynn/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v14.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/fred/.nvm/versions/node/v14.4.0/bin/node /home/fred/.nvm/versions/node/v14.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/fred/Wavynn/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31/opus.node --module_name=opus --module_path=/home/fred/Wavynn/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-2.31 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fred/.npm/_logs/2020-10-25T15_34_16_816Z-debug.log
```

**Further details:**

- @discordjs/opus version:
- Node.js version: v14.4.0
- Operating system: WSL - Linux
- Priority this issue should have – please be realistic and elaborate if possible: I can wait, might be an issue on my side, if WSL 1 isn't supported

**Comment by iCrawl** [comment]
> gyp ERR! stack Error: not found: make

Please install `make` on your system for this to work.
Generally speaking this should be included in some sort of build tool package of your distro.

**Comment by FredTheNoob** [comment]
Thank you,

I installed make on ubuntu and now I am recieving this error, along lots of warnings:

```js
make: Leaving directory '/home/fred/Wavynn/node_modules/@discordjs/opus/build'
node-pre-gyp ERR! UNCAUGHT EXCEPTION 
node-pre-gyp ERR! stack Error: EACCES: permission denied, rename 'build' -> 'build-tmp-napi-v3'
node-pre-gyp ERR! stack     at Object.renameSync (fs.js:756:3)
node-pre-gyp ERR! stack     at Object.module.exports.swap_build_dir_out (/home/fred/Wavynn/node_modules/@discordjs/node-pre-gyp/lib/util/napi.js:178:6)
node-pre-gyp ERR! stack     at /home/fred/Wavynn/node_modules/@discordjs/node-pre-gyp/lib/build.js:23:10
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/fred/Wavynn/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:74:3)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/home/fred/.nvm/versions/node/v14.4.0/bin/node" "/home/fred/Wavynn/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/fred/Wavynn/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v14.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! This is a bug in `node-pre-gyp`.
node-pre-gyp ERR! Try to update node-pre-gyp and file an issue if it does not help:
node-pre-gyp ERR!     <https://github.com/mapbox/node-pre-gyp/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! @discordjs/opus@0.3.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fred/.npm/_logs/2020-10-25T16_55_24_113Z-debug.log
```

**Comment by FredTheNoob** [comment]
I managed to fix the error, for anyone else I installed make like this:

```
sudo apt-get install build-essential
```

From there I allowed unsafe perms with npm:
```
npm config set unsafe-perm true
```
