### ISSUE TITLE
Does not install properly.

### ISSUE THREAD

**Issue by cxnvr** [discordjs/opus#58]
**Please describe the problem you are having in as much detail as possible:**
When I go to install the npm package it gives tons of errors.
**Include a reproducible code sample here, if possible:**

```js
npm ERR! code 1
npm ERR! path E:\MUSICBot\node_modules\@discordjs\opus
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\MUSICBot\node_modules\@discordjs\opus\prebuild\node-v88-napi-v3-win32-x64-unknown-{libc_version}\opus.node --module_name=opus --module_path=E:\AJHSBot\node_modules\@discordjs\opus\prebuild\node-v88-napi-v3-win32-x64-unknown-{libc_version} --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.17.0
npm ERR! node-pre-gyp info using node@15.5.1 | win32 | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "E:\MUSICBot\node_modules\@discordjs\opus\prebuild\node-v88-napi-v3-win32-x64-unknown-{libc_version}\opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v88-napi-v3-win32-x64-unknown-%7Blibc_version%7D.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v88-napi-v3-win32-x64-unknown-%7Blibc_version%7D.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v88-napi-v3-win32-x64-unknown-%7Blibc_version%7D.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.3 and node@15.5.1 (node-v88 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v88-napi-v3-win32-x64-unknown-%7Blibc_version%7D.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.5.1 | win32 | x64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.5.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.1 found at "C:\Users\Conor\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:340:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\\MUSICBot\\node_modules\\@discordjs\\opus\\prebuild\\node-v88-napi-v3-win32-x64-unknown-{libc_version}\\opus.node" "--module_name=opus" "--module_path=E:\\MUSICBot\\node_modules\\@discordjs\\opus\\prebuild\\node-v88-napi-v3-win32-x64-unknown-{libc_version}" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd E:\MUSICBot\node_modules\@discordjs\opus
npm ERR! gyp ERR! node -v v15.5.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\MUSICBot\node_modules\@discordjs\opus\prebuild\node-v88-napi-v3-win32-x64-unknown-{libc_version}\opus.node --module_name=opus --module_path=E:\MUSICBot\node_modules\@discordjs\opus\prebuild\node-v88-napi-v3-win32-x64-unknown-{libc_version} --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (E:\MUSICBot\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1063:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.19042
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\MUSICBot\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd E:\MUSICBot\node_modules\@discordjs\opus
npm ERR! node-pre-gyp ERR! node -v v15.5.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.17.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Conor\AppData\Local\npm-cache\_logs\2021-01-09T20_25_38_955Z-debug.log
```

**Further details:**
As Seen in the code above the package does not work. I have all of the dependencies installed as well.
- @discordjs/opus version: 0.3.3
- Node.js version: 15.5.1
- Operating system: Unactivated Microsoft Windows 10 Home 64 Bit
- Priority this issue should have – please be realistic and elaborate if possible:
Medium as this does not install on a normal build of Windows 10, a very common operating system.

**Comment by papaia** [comment]
>You need to install the latest version of Visual Studio
including the "Desktop development with C++" workload.

**Comment by Ricozyx** [comment]
So how are people supposed to host their bots in Ubuntu servers?

**Comment by aggraith** [comment]
Use node.js version 14.15.5

I don't think this package has support for the latest node version.

**Comment by advaith1** [comment]
that error message is specifically from Node on Windows; not sure what this has to do with Ubuntu or node versions, as those are unrelated to the error message in the issue description (which again, is from Node, not d.js)

**Comment by aggraith** [comment]
> that error message is specifically from Node on Windows; not sure what this has to do with Ubuntu or node versions, as those are unrelated to the error message in the issue description (which again, is from Node, not d.js)

I said that comment because this is the #1 google search when u copy the error output. So that people know that the error comes from node.js ver 15. So to use the recommended ver of node.js instead

**Comment by iCrawl** [comment]
No it's really not an issue with Node v15, it's an issue that they don't have proper build tools installed.

**Comment by Everysimo** [comment]
i'm having the same problem with node v12.19.1
