### ISSUE TITLE
Can't install 0.5.0 using Linux arm64

### ISSUE THREAD

**Issue by Scyboi** [discordjs/opus#79]
Cannot install @discordjs/opus due to lack of arm64 version of 0.5.0 release.

```js
ubuntu@ubuntu:~/Scarlet Clean$ sudo npm i @discordjs/opus --unsafe-perm true

> @discordjs/opus@0.5.0 install /home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v83-napi-v3-linux-arm64-glibc-2.31.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.0 and node@14.15.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v83-napi-v3-linux-arm64-glibc-2.31.tar.gz 
gyp: binding.gyp not found (cwd: /home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-1028-raspi
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm64-glibc-2.31/opus.node" "--module_name=opus" "--module_path=/home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm64-glibc-2.31" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm64-glibc-2.31/opus.node --module_name=opus --module_path=/home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm64-glibc-2.31 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/Scarlet Clean/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-1028-raspi
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/ubuntu/Scarlet Clean/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v14.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.3.2
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm64-glibc-2.31/opus.node --module_name=opus --module_path=/home/ubuntu/Scarlet Clean/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-arm64-glibc-2.31 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN Scarlet Clean No description
npm WARN Scarlet Clean No repository field.
npm WARN Scarlet Clean No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @discordjs/opus@0.5.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @discordjs/opus@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-26T22_16_39_118Z-debug.log
```

**System:**
- @discordjs/opus version: none
- Node.js version: 14.15.0
- Operating system: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-1028-raspi aarch64)
- Priority: Medium

**Comment by Tjum28** [comment]
I have the same problem that I can't install opus :(

**Comment by Ipmake123** [comment]
I have the same Issue. Any fixes?

**Comment by iCrawl** [comment]
You shouldn't use sudo to install anything from npm.

But apart from that, that error log is not helpful. Try upgrading your node version.

**Comment by hofmmaxi** [comment]
But even without using `sudo` you still get an error.
And also tried using node Latest, as well as LTS, but both didn't work.

```zsh
hofmmaxi@Maximilians-Mac-mini canary-bot % npm i @discordjs/opus
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
npm ERR! Failed to execute '/Users/hofmmaxi/.nvm/versions/node/v15.14.0/bin/node /Users/hofmmaxi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.3.2
npm ERR! node-pre-gyp info using node@15.14.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown/opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v88-napi-v3-darwin-arm64-unknown-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v88-napi-v3-darwin-arm64-unknown-unknown.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.5.0 and node@15.14.0 (node-v88 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.5.0/opus-v0.5.0-node-v88-napi-v3-darwin-arm64-unknown-unknown.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | darwin | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.4 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/hofmmaxi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/hofmmaxi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/hofmmaxi/Library/Caches/node-gyp/15.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/hofmmaxi/Library/Caches/node-gyp/15.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/hofmmaxi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/hofmmaxi/Library/Caches/node-gyp/15.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@15.14.0 | darwin | arm64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! ../deps/opus/src/opus_multistream.c:29:10: fatal error: 'config.h' file not found
npm ERR! #include "config.h"
npm ERR!          ^~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/libopus/deps/opus/src/opus_multistream.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/hofmmaxi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 20.4.0
npm ERR! gyp ERR! command "/Users/hofmmaxi/.nvm/versions/node/v15.14.0/bin/node" "/Users/hofmmaxi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown/opus.node" "--module_name=opus" "--module_path=/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus
npm ERR! gyp ERR! node -v v15.14.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/hofmmaxi/.nvm/versions/node/v15.14.0/bin/node /Users/hofmmaxi/.nvm/versions/node/v15.14.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown/opus.node --module_name=opus --module_path=/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus/prebuild/node-v88-napi-v3-darwin-arm64-unknown-unknown --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:369:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.4.0
npm ERR! node-pre-gyp ERR! command "/Users/hofmmaxi/.nvm/versions/node/v15.14.0/bin/node" "/Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/hofmmaxi/Documents/Coding/Projects/Discord/canary-bot/node_modules/@discordjs/opus
npm ERR! node-pre-gyp ERR! node -v v15.14.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.3.2
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hofmmaxi/.npm/_logs/2021-04-16T20_15_23_177Z-debug.log```

**Comment by iCrawl** [comment]
You should not even get this warning:
> npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

Make sure you clean out your npm cache and node_modules

**Comment by Tilto0822** [comment]
In my case, resolved the problem by update @discordjs/opus module's version to ^0.5.0
