### ISSUE TITLE
Installation Issue w/ node-pre-gyp errors

### ISSUE THREAD

**Issue by LONGLOSTBRAH** [discordjs/opus#96]
I have been on this for a few hours now and can't really find any threads that have helped in any way. To be honest I'm not sure exactly what I'm looking for within the errors however I still tried looking stuff up before coming here and I couldn't find anything that helps.

I have tried a few things so far:

- Made sure the correct dependencies/packages are installed.
- Tried both the latest and recommended versions of nodejs
- Tried installed a different version of discordjs/opus

No matter what I tried the errors stayed the same. 

<details>
<summary><b>Errors</b></summary>

```
# npm i @discordjs/opus
npm ERR! code 1
npm ERR! path /root/discord/lost-bot/node_modules/@discordjs/opus
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! make: Entering directory '/root/discord/lost-bot/node_modules/@discordjs/opus/build'
npm ERR!   CC(target) Release/obj.target/libopus/deps/opus/src/opus_multistream.o
npm ERR! deps/libopus.target.mk:304: recipe for target 'Release/obj.target/libopus/deps/opus/src/opus_multistream.o' failed
npm ERR! make: Leaving directory '/root/discord/lost-bot/node_modules/@discordjs/opus/build'
npm ERR! Failed to execute '/usr/local/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/discord/lost-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-{libc_version}/opus.node --module_name=opus --module_path=/root/discord/lost-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-{libc_version} --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.17.0
npm ERR! node-pre-gyp info using node@14.17.3 | linux | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/root/discord/lost-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-{libc_version}/opus.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v83-napi-v3-linux-x64-glibc-%7Blibc_version%7D.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v83-napi-v3-linux-x64-glibc-%7Blibc_version%7D.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v83-napi-v3-linux-x64-glibc-%7Blibc_version%7D.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.5.3 and node@14.17.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/discordjs/opus/releases/download/v0.5.3/opus-v0.5.3-node-v83-napi-v3-linux-x64-glibc-%7Blibc_version%7D.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.3 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.3 | linux | x64
npm ERR! gyp info find Python using Python version 3.5.2 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v14.17.3/node-v14.17.3-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.17.3/node-v14.17.3-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v14.17.3/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v14.17.3/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/discord/lost-bot/node_modules/@discordjs/opus/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/14.17.3/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.17.3',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.17.3/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/discord/lost-bot/node_modules/@discordjs/opus',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.3 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: cc: Command not found
npm ERR! make: *** [Release/obj.target/libopus/deps/opus/src/opus_multistream.o] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Linux 2.6.32-042stab145.3
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/root/discord/lost-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-{libc_version}/opus.node" "--module_name=opus" "--module_path=/root/discord/lost-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-{libc_version}" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /root/discord/lost-bot/node_modules/@discordjs/opus
npm ERR! gyp ERR! node -v v14.17.3
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/root/discord/lost-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-{libc_version}/opus.node --module_name=opus --module_path=/root/discord/lost-bot/node_modules/@discordjs/opus/prebuild/node-v83-napi-v3-linux-x64-glibc-{libc_version} --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/root/discord/lost-bot/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! node-pre-gyp ERR! System Linux 2.6.32-042stab145.3
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/root/discord/lost-bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /root/discord/lost-bot/node_modules/@discordjs/opus
npm ERR! node-pre-gyp ERR! node -v v14.17.3
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.17.0
npm ERR! node-pre-gyp ERR! not ok
```
</details>

**Further details:**

@discordjs/opus version: All
Node.js version: 14 to 16.5.0
Operating system: Ubuntu 16.04.1
Priority this issue should have – please be realistic and elaborate if possible: **Low Priority** - Working on a personal project with no rush.

**Comment by KodySalak** [comment]
I am having this same exact issue and I cannot seem to get around it. I had python3 installed and I had removed it for troubleshooting purposes without any change. I am running Node 14.17.5 on CentOS7 fully updated. See attached log file. 
[2021-08-28T23_57_39_123Z-debug.log](https://github.com/discordjs/opus/files/7072002/2021-08-28T23_57_39_123Z-debug.log)
